### ISSUE TITLE
SSUPayloadType/SSUSession copypasta

### ISSUE THREAD

**Issue by anonimal** [EinMByte/kovri#3]
I've opened an issue here so we can coordinate until we merge with upstream.

**Edit**: I'll try to open tickets that are issue-specific instead of a catch-all issue for all our correspondence.

Referencing https://github.com/monero-project/kovri/issues/140.

**Comment by anonimal** [comment]
Why do we set header [payload type](https://github.com/EinMByte/kovri/blob/ssu/src/core/transport/SSUPacket.h#L82) to `SessionRequest` for [SendSessionCreated()](https://github.com/EinMByte/kovri/blob/ssu/src/core/transport/SSUSession.cpp#L419) and 
[SendSessionConfirmed()](https://github.com/EinMByte/kovri/blob/ssu/src/core/transport/SSUSession.cpp#L515)?

**Comment by EinMByte** [comment]
@anonimal My guess is because copy-pasta :p.

**Comment by anonimal** [comment]
:spaghetti: :fork_and_knife:  lol, thought so, it happens :wink:

**Comment by anonimal** [comment]
Note: I still can't get SSU working with the correct headers. IMHO, we don't yet have enough error reporting in `SSUSession` so any obvious errors will take longer to debug (at least for me).
